name: "rating_dbt"
version: "1.0.0"
config-version: 2

profile: "rating_postgres"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  rating_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table