[destination.postgres.credentials]
database = "<DATABASE_NAME>"
username = "postgres"
password = "<PASSWORD>"
host = "localhost"
port = 5432

[sources.mssql]
connection_string = "mssql+pyodbc://@<HOST_NAME>/AdventureWorks2025?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes&Encrypt=yes&TrustServerCertificate=yes"

[sources.csv_reviews]
path = "zad1/SBI2526-LAB-Rating-FixedDate.csv"
